export const exercises = [
  {
    id: 1,
    name: "Bench Press",
    muscle: "Chest",
    equipment: "Barbell",
    difficulty: "Intermediate",
    type: "Compound",
  },
  {
    id: 2,
    name: "Incline Dumbbell Press",
    muscle: "Chest",
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    type: "Compound",
  },
  {
    id: 3,
    name: "Cable Crossover",
    muscle: "Chest",
    equipment: "Cable",
    difficulty: "Beginner",
    type: "Isolation",
  },
  {
    id: 4,
    name: "Barbell Squat",
    muscle: "Legs",
    equipment: "Barbell",
    difficulty: "Intermediate",
    type: "Compound",
  },
  {
    id: 5,
    name: "Leg Press",
    muscle: "Legs",
    equipment: "Machine",
    difficulty: "Beginner",
    type: "Compound",
  },
  {
    id: 6,
    name: "Romanian Deadlift",
    muscle: "Hamstrings",
    equipment: "Barbell",
    difficulty: "Intermediate",
    type: "Compound",
  },
  {
    id: 7,
    name: "Lat Pulldown",
    muscle: "Back",
    equipment: "Cable",
    difficulty: "Beginner",
    type: "Compound",
  },
  {
    id: 8,
    name: "Barbell Row",
    muscle: "Back",
    equipment: "Barbell",
    difficulty: "Intermediate",
    type: "Compound",
  },
  {
    id: 9,
    name: "Lateral Raise",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    difficulty: "Beginner",
    type: "Isolation",
  },
  {
    id: 10,
    name: "Shoulder Press",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    type: "Compound",
  },
  {
    id: 11,
    name: "Barbell Curl",
    muscle: "Biceps",
    equipment: "Barbell",
    difficulty: "Beginner",
    type: "Isolation",
  },
  {
    id: 12,
    name: "Tricep Pushdown",
    muscle: "Triceps",
    equipment: "Cable",
    difficulty: "Beginner",
    type: "Isolation",
  },
];